version: '3'
services:
  app:
    container_name: guess-number
    image: guess-number:v1
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/redis:/guess-number/logs
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"